### ISSUE TITLE
Add a sticky top nav?

### ISSUE THREAD

**Issue by Lemmings19** [thatsmybis/thatsmybis#269]
I tried implementing quickly, but there's some QA and UX issues. Once implemented, clicking on the top menu jumped the page to the top... which is problematic.

https://discord.com/channels/732998376798552210/733019346649088121/926282680780333117

**Comment by papa-smurf** [comment]
@Lemmings19 as mentioned [on Discord](https://discord.com/channels/732998376798552210/733019346649088121/1009367973435277333) by Briathos#5507 the page jumping around is caused by the `href="#"` part, replacing it with `href="javascript:void(0)"` seems to do the trick together with the following attributes on the `.navbar` class:

```css
position: fixed;
width: 100%;
top: -1px;
z-index: 500;
background-color: rgba(255,255,255,0.2);
-webkit-backdrop-filter: blur(2px);
backdrop-filter: blur(2px);
```

Do keep in mind that making the navbar sticky creates some collision issues on some pages' `h1` title:

![image](https://user-images.githubusercontent.com/4224975/185080578-f75cd9f3-b400-460e-b644-05437cd3e077.png)

**Comment by Lemmings19** [comment]
@papa-smurf `href="javascript:void(0)"` fixes the main issue, thanks.
