### ISSUE TITLE
Loot received list vs Received checkbox on wishlist and on prio list aren't connected

### ISSUE THREAD

**Issue by Jakobud** [thatsmybis/thatsmybis#289]
**Describe the bug**
It seems like there are 3 different ways that one can tell TMB that they have received an item and they don't seem to be connected properly in the database:

1. On a wishlist, you can mark an item as "Received" with the checkbox
2. You can add an item to your "Loot Received" list
3. You can mark "Received" for an item on a Prio list

None of the items appear to be interconnected in the database. When you checkmark "Received" in the wishlist, it crosses it out in the UI but doesn't add the item to Loot Received. Why? Same thing with the "Received" checkbox on the prio lists. Checking it doesn't do anything else. However you when Add an item to Loot Received it does automatically check the boxes for "Received" on both the wishlist and prio'ed list. But if you then uncheck either of those the opposite action (item should be removed from the loot received list) does not happen.

**Expected behavior**
From a usability/UX approach, there should only be a single way that you tell TMB that an item was received by a character. There shouldn't be 3 different ways. You can definitely have different ways of showing that an item was received, like crossing it off the list or checking a read-only checkbox or something like that. But there needs to be just a single way to actually indicate if you have or have not received an item.

Related bug: When you check an item on a prio list that it was received why would this character not be removed from the prio list for this item? When would this ever make sense?

**Comment by Lemmings19** [comment]
> However you when Add an item to Loot Received it does automatically check the boxes for "Received" on both the wishlist and prio'ed list.
This fulfills the action of a player receiving an item in the same way as if they received it via the "Assign Loot" page. If they have received the item, the system assumes it is safe to mark it as received on the player's wishlist and prio list.

> But if you then uncheck either of those the opposite action (item should be removed from the loot received list) does not happen.
Guilds and players may wish to manually intervene or override the configuration of prios and wishlists.

For the case of manipulating the metadata on wishlists and prio lists: perhaps a mistake was made, Perhaps a player wanted to get two of that item instead of one. Perhaps they traded the item off. There could be a number of use cases.

Assuming which action is taking place here is considered more risky. So the system takes a hands off approach and allows the user fine grain control; however they see fit.

**Comment by Lemmings19** [comment]
I do generally agree that a single source of truth is ideal. Perhaps if I were to go back and rebuild the website from scratch, I would implement this. However, these features were added in piecemeal over a few years as people requested them. This may be an unfortunate side effect, however some users may appreciate the more fine-grain control. /shrug
