### ISSUE TITLE
Prio does not change when dragging/dropping character order

### ISSUE THREAD

**Issue by Jakobud** [thatsmybis/thatsmybis#290]
**Describe the bug**
Wherever there is a drag/drop list of prio'ed characters for an item, simply dragging/dropping the characters to change the order does not save the order

**To Reproduce**
1. On prio list for item, drag/drop characters to change their prio order
2. Hit Submit button
3. See that the order did not update

**Expected behavior**
It saved the order you specified

**Additional context**
When you manually change the integer number order in the list instead of drag/drop it does save properly.

**Comment by Lemmings19** [comment]
![image](https://user-images.githubusercontent.com/3407841/200690725-4e1bb48b-6d95-437e-8d6c-4e42514feb47.png)

My best guess is that the behaviour you are describing is when there are (white) numbers inside the numeric boxes. I have been unable to reproduce this behaviour when there aren't any numbers in those boxes.

Those numbers are intended as a manual override of whatever physical positioning is in the list. (this is to allow for ties; eg. multiple people at rank  number 1)

Side note: I am guessing that numbers can be added to those boxes outside of your control when loot is distributed and the system is set to **delete** prios when they are fulfilled. The system will put in overriding numbers to preserve the old prio ordering rather than letting them get bumped up. I am planning on adding an option to skip this behaviour.

Let me know if I am wrong or missed something.
