### ISSUE TITLE
Allow raid leads to order characters by priority for any given item

### ISSUE THREAD

**Issue by Lemmings19** [thatsmybis/thatsmybis#8]
For each item in an instance, leadership should be able to set a list of characters waiting in line for that item, and in what order those characters are.

This will require changes to the database, models, controllers, and views.

This is a high priority task, as it has been requested several times and makes sense to add.

**Comment by Pyrodius0** [comment]
Looking at this a bit more, we will have to change up the page quite a bit to accomplish this. 

Couple Thoughts: 

1. If a guild prioritizes an item to a player, we should not allow that item to be removed from the wishlist of the player. If they try to remove the item, we should point them to talk to the loot council to remove their priority first. This makes sure people dont remove items and LC is not aware. 

2. Since we need to prioritize the items by Raid, we either need to change the Wishlist section to create a table per raid and then manage the prioritization from there or create a new table on the page that allows the loot council to change which raid they are looking at and show the prioritization. 

I am leaning towards a new table on the page..

**Comment by Lemmings19** [comment]
For the input, I'm thinking we use a new page. You choose your raid before loading the page:
![image](https://user-images.githubusercontent.com/3407841/90289535-ee896680-de30-11ea-9eaf-eb07a5509a9d.png)

I had an alternate version where one page can be used to edit all raids, but it would be messier to implement and more error prone. It would also present a problem where multiple raid leads couldn't be editing raids at the same time (risk of data being overwritten):
![image](https://user-images.githubusercontent.com/3407841/90289473-cef23e00-de30-11ea-8e9e-2b04b96a01b1.png)

As for navigating to the page, maybe something like this makes sense:
![image](https://user-images.githubusercontent.com/3407841/90290201-45437000-de32-11ea-9be8-a79215f51170.png)

I have to step away from my computer right now, but next I'll have a look at how this will interact with wishlists... I'm not so sure this feature can properly overlap with wishlists. The purpose of a wishlist is different from this: it's to give raiders the opportunity to let loot council know what they want. Overriding the wishlist with this feature might put the wishlist in a bad state.

**Comment by Pyrodius0** [comment]
We can do the priority list in a different page.. but we still need to display the priority on the item page as well as provide a quick way to assign the loot to a player from the same page.

**Comment by Lemmings19** [comment]
For displaying the priority, I propose we introduce a "Prio'd" section. So when viewing a character, you see Wishlist (items they wishlisted), Prio'd (items an officer has set them as priority for), and Received.

When viewing an item or the item list page for an instance (eg. AQ), we introduce a new column for Prio'd players, in order of priority and separated by raid. Same for the roster page.

When assigning loot to a player via the Assign Loot page, it currently attempts to remove one of that item from the player's wishlist when they received it. We can have it also attempt to remove one of that item from the player's prio'd items.

Regarding having a quick way to assign loot, I presume you mean to say choose the raider prio's for that item. We can have a subsection of the new page, but only for that one item, and require them to specify the raid before letting them edit the form. (however I haven't thought much about this section yet)

If you meant assign loot as in actually give it to them, I think that's a different feature and a different PR. Definitely an important PR, but should be tackled separate from this.

**Comment by Pyrodius0** [comment]
> For displaying the priority, I propose we introduce a "Prio'd" section. So when viewing a character, you see Wishlist (items they wishlisted), Prio'd (items an officer has set them as priority for), and Received.

Yeah, I think this is a good addition to the feature. 

> When viewing an item or the item list page for an instance (eg. AQ), we introduce a new column for Prio'd players, in order of priority and separated by raid. Same for the roster page.

>When assigning loot to a player via the Assign Loot page, it currently attempts to remove one of that item from the player's wishlist when they received it. We can have it also attempt to remove one of that item from the player's prio'd items.

Yes, it should do the same thing to the priority list as it does to the wishlist. 

> Regarding having a quick way to assign loot, I presume you mean to say choose the raider prio's for that item. We can have a subsection of the new page, but only for that one item, and require them to specify the raid before letting them edit the form. (however I haven't thought much about this section yet)

>If you meant assign loot as in actually give it to them, I think that's a different feature and a different PR. Definitely an important PR, but should be tackled separate from this.


I am specifically talking about the second one here.. and yes it is a different request and PR. But, we do need to take it into account when we are adding new stuff to this page. 

I want to be careful that we don't require the end user to click to 15 different places in the application to manage one piece of loot. 

Example: We are saying that a officer will have to open up a Prio page to assign priority to a player, while at the same time  having to have the item page open to see who has it on their wishlist, and then the officer will open the item during raid, see who needs it, then have to go to assign loot page to assign the player. 

We should be focused on trying to make it easy to manage an item from a single place instead of adding extra places that end users have to continually navigate around to manage one piece of loot. 

I do understand this adds complexity and bug area, but we need to consider the trade off of usability vs catering the design to bug surface area.

**Comment by Pyrodius0** [comment]
> For the input, I'm thinking we use a new page. You choose your raid before loading the page:
> ![image](https://user-images.githubusercontent.com/3407841/90289535-ee896680-de30-11ea-9eaf-eb07a5509a9d.png)


Also a thought about this page. Specifically for our guild, we decide the priority by understanding the wishlist from each player. This seems painful to have to manage multiple pages for assigning priority.

**Comment by Lemmings19** [comment]
I wrote a wall of text. Then I deleted it and tried to write it shorter. I wrote another wall of text.

Let's have a call to discuss.
